// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkf1ZfLKF_OLD-uEdojhJzEvkoxYyRatM',
    appId: '1:80479214894:web:7b01c03a98f589d6b32ebf',
    messagingSenderId: '80479214894',
    projectId: 'sound-guide-app',
    authDomain: 'sound-guide-app.firebaseapp.com',
    storageBucket: 'sound-guide-app.firebasestorage.app',
    measurementId: 'G-B0VSXW87SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ40Ly_FpCk1VK69_3TDPgr6UyPOyg124',
    appId: '1:80479214894:android:295307a83d9b9072b32ebf',
    messagingSenderId: '80479214894',
    projectId: 'sound-guide-app',
    storageBucket: 'sound-guide-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf8kpc4Ta8Ni2P1E9k_6qkpult0HTPeSU',
    appId: '1:80479214894:ios:6ed9f0dce9b6b2a2b32ebf',
    messagingSenderId: '80479214894',
    projectId: 'sound-guide-app',
    storageBucket: 'sound-guide-app.firebasestorage.app',
    iosClientId: '80479214894-uucbm2iou0l8ticpg5lbfc92bg988mvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundguideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf8kpc4Ta8Ni2P1E9k_6qkpult0HTPeSU',
    appId: '1:80479214894:ios:6ed9f0dce9b6b2a2b32ebf',
    messagingSenderId: '80479214894',
    projectId: 'sound-guide-app',
    storageBucket: 'sound-guide-app.firebasestorage.app',
    iosClientId: '80479214894-uucbm2iou0l8ticpg5lbfc92bg988mvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundguideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkf1ZfLKF_OLD-uEdojhJzEvkoxYyRatM',
    appId: '1:80479214894:web:9e29439856cd6730b32ebf',
    messagingSenderId: '80479214894',
    projectId: 'sound-guide-app',
    authDomain: 'sound-guide-app.firebaseapp.com',
    storageBucket: 'sound-guide-app.firebasestorage.app',
    measurementId: 'G-5SDB78FL89',
  );
}
